spring:
  datasource:
    url: jdbc:mysql://115.120.221.163:3306/office_plan?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: hht500234
  redis:
    host: 115.120.221.163 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mail:
    host: smtp.qq.com
    port: 587
    username: aidenz233@qq.com
    password: kiwrwbsmpcenjddb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    root: info
    com.macro.mall: debug

upload:
  directory: static

baidu:
  api:
    key: PteXuiZlsm9Q3pE1hZJfnrZt
  secret:
    key: bb09UXEZbpJdWN4tMWcjbT2TsQunI387